---
# Adjust this based on your release workflow
# 👋 Look here for another good example: https://github.com/bytecodealliance/wasmtime-rb/tree/main/.github/workflows
name: Cross Gem
on:
  workflow_dispatch:
    inputs:
      rb-sys-branch:
        description: 'rb-sys branch to test against'
        required: false
        default: 'main'
        type: string
  push:
    branches: ["main", "cross-gem/*"]

jobs:
  ci-data:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.fetch.outputs.result }}
    steps:
      # This compiles for all supported Ruby cross-compilation platforms.
      - id: fetch
        uses: oxidize-rb/actions/fetch-ci-data@main
        with:
          supported-ruby-platforms: |
            exclude: []

  cross_gems:
    name: Cross compile gems
    needs: ci-data
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-platform: ${{ fromJSON(needs.ci-data.outputs.result).supported-ruby-platforms }}
    steps:
      - uses: actions/checkout@v3

      - uses: "ruby/setup-ruby@v1"
        with:
          ruby-version: "3.2"

      - name: Patch rb-sys version
        run: |
          mkdir -p .cargo
          echo "[patch.crates-io]" >> .cargo/config.toml
          echo "rb-sys = { git = \"https://github.com/oxidize-rb/rb-sys\", branch = \"${{ github.events.inputs.rb-sys-branch }}\" }" >> .cargo/config.toml
          echo "rb-sys-env = { git = \"https://github.com/oxidize-rb/rb-sys\", branch = \"${{ github.events.inputs.rb-sys-branch }}\" }" >> .cargo/config.toml
          sed -i "s|gem 'rb_sys', '.*'|gem 'rb_sys', github: 'oxidize-rb/rb-sys', branch: '${{ github.events.inputs.rb-sys-branch }}'|g" Gemfile
          bundle install --jobs 4 --retry 3
          cargo update -p rb-sys

      - uses: oxidize-rb/actions/cross-gem@v1
        with:
          platform: ${{ matrix.ruby-platform }}

      - uses: actions/upload-artifact@v3
        with:
          name: cross-gem-${{ matrix.ruby-platform }}
          path: pkg/*-${{ matrix.ruby-platform }}.gem
          if-no-files-found: error
          retention-days: 1

      - name: "Copy bindings and cfg-capture"
        id: capture
        run: |
          outdir=tmp/upload/${{ matrix.ruby-platform }}
          mkdir -p $outdir

          echo "::group::Copy bindings"
          find target/ -name "bindings*" -exec cp {} $outdir/artifacts \;
          echo "::endgroup::"

          echo "::group::Copy cfg-capture"
          find target/ -name "cfg-capture*" -exec cp {} $outdir/artifacts \;
          echo "::endgroup::"

          echo "::group::Copy Build config"
          cp -r tmp/ $outdir/tmp
          echo "::endgroup::"

          echo "rb-sys-version=$(bundle exec rb-sys-dock --version)" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v3
        with:
          name: rb-sys-bindings-${{ steps.capture.outputs.rb-sys-version }}
          path: |
            tmp/upload/
          if-no-files-found: error
